apiVersion: v1
kind: Service
metadata:
  name: test-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test.k8s.ozalp.dk
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-app
---
apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80