apiVersion: v1
kind: Service
metadata:
  name: test-dns
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test9.k8s.ozalp.dk
    external-dns.alpha.kubernetes.io/ttl: "3710"
    external-dns.alpha.kubernetes.io/comment: "test comment"
    external-dns.alpha.kubernetes.io/record-weight: "42"
    external-dns.alpha.kubernetes.io/provider-specific: '[{"name":"test-dns","value":"25465820"}]'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: test-app
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: test-user-prop
  namespace: default
spec:
  endpoints:
  - dnsName: test-user-prop.k8s.ozalp.dk
    recordType: A
    targets:
    - 10.0.0.1
    recordTTL: 300