apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-dns-simply.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns-simply.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "external-dns-simply.externalDns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "external-dns-simply.externalDns.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "external-dns-simply.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: external-dns
          image: "{{ .Values.externalDns.image.repository }}:{{ .Values.externalDns.image.tag }}"
          imagePullPolicy: {{ .Values.externalDns.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          args:
            {{- range .Values.externalDns.sources }}
            - --source={{ . }}
            {{- end }}
            {{- if .Values.domainFilter }}
            - --domain-filter={{ .Values.domainFilter }}
            {{- end }}
            - --provider=webhook
            - --webhook-provider-url=http://{{ include "external-dns-simply.webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.webhook.port }}
            - --policy={{ .Values.externalDns.policy }}
            - --registry={{ .Values.externalDns.registry }}
            - --txt-owner-id={{ .Values.externalDns.txtOwnerId }}
            - --interval={{ .Values.externalDns.interval }}
            - --log-level={{ .Values.externalDns.logLevel }}
            {{- if .Values.externalDns.publishInternalServices }}
            - --publish-internal-services
            {{- end }}
            {{- if .Values.externalDns.publishNotReadyAddresses }}
            - --always-publish-not-ready-addresses
            {{- end }}
            {{- range .Values.externalDns.extraArgs }}
            - {{ . }}
            {{- end }}
          resources:
            {{- toYaml .Values.externalDns.resources | nindent 12 }}
