apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-dns-simply.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns-simply.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webhook.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "external-dns-simply.selectorLabels" . | nindent 4 }}
